name             'nginx-config'
maintainer       'PMSIpilot'
maintainer_email 'support@pmsipilot.com'
license          'MIT'
description      'Configures nginx'
long_description 'Configures nginx'
version          '1.0.0'
